### ISSUE TITLE
TimeOverlapFinder is not able to access in the main

### ISSUE THREAD

**Issue by XeroDays** [manthri-mohan-sai/time_overlapping#3]
`print(TimeOverlapFinder.findOverlap(overlapParams));`

Cannot access the TimeOverlapFinder function, 
i have tried the import and also intellisense.. 
but not able to call or access the assembly.

**Comment by manthri-mohan-sai** [comment]
@XeroDays I really appreciate if you can share the screenshot of the error which helps me to understand the issue much better
