### ISSUE TITLE
findOverlap function does not ignore seconds and even microseconds

### ISSUE THREAD

**Issue by codewithmustafa** [manthri-mohan-sai/time_overlapping#4]
In my tests the findOverlap function is not ignoring seconds even with its ignoreSeconds parameter set true. I tested furtherly and see it does calculate microseconds too.

**Comment by codewithmustafa** [comment]
Here is my dynamically generated overlapParams list:

`0 = {OverlapParams} OverlapParams(fc6ebd98-1b16-40fd-b0ab-a3da60f035a6, 2023-05-17 00:00:00.000 - 2023-05-17 18:00:00.000, {})
1 = {OverlapParams} OverlapParams(db1480b0-77e8-4aca-9f88-4b13a718583b, 2023-05-17 18:00:00.299990 - 2023-05-17 19:00:00.299990, {})
2 = {OverlapParams} OverlapParams(906ec46c-d62d-4b54-8467-e9a8d8dda426, 2023-05-17 19:00:00.000 - 2023-05-17 23:59:00.000, {})`

**Comment by codewithmustafa** [comment]
Here is my dynamically generated overlapParams list:

[OverlapParams(fc6ebd98-1b16-40fd-b0ab-a3da60f035a6, 2023-05-17 00:00:00.000 - 2023-05-17 18:00:00.000, {}),
OverlapParams(db1480b0-77e8-4aca-9f88-4b13a718583b, 2023-05-17 18:00:00.299990 - 2023-05-17 19:00:00.299990, {}),
OverlapParams(906ec46c-d62d-4b54-8467-e9a8d8dda426, 2023-05-17 19:00:00.000 - 2023-05-17 23:59:00.000, {})]

With this it returns true (says has overlap).

**Comment by manthri-mohan-sai** [comment]
Hi @codewithmustafa, When you set `ignoreSeconds` to true, it sets seconds, milliseconds, and microseconds to 0.

Here is whats happening in your case, when you set the `ignoreSeconds` to true, the data becomes 
```dart
[
  OverlapParams(fc6ebd98-1b16-40fd-b0ab-a3da60f035a6, 2023-05-17 00:00:00.000 - 2023-05-17 18:00:00.000, {}),
  OverlapParams(db1480b0-77e8-4aca-9f88-4b13a718583b, 2023-05-17 18:00:00.00 - 2023-05-17 19:00:00:00, {}),
  OverlapParams(906ec46c-d62d-4b54-8467-e9a8d8dda426, 2023-05-17 19:00:00.000 - 2023-05-17 23:59:00.000, {}),
]
```

Now, you need to make sure `allowTouches` set to True to gives you result hasOverlap false

```dart
allowTouches: true // hasOverlap is false
allowTouches: false // hasOverlap is true

```

> The allowTouches parameter determines whether it is acceptable for the end time of one range to be equal to the start time of another range. For example, [1, 5] and [5, 10] are considered overlapping if allowTouches is false.


Please free to reopen this ticket if you have any additional queries
